# Generated by Django 5.0.3 on 2024-03-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Departments',
            new_name='Department',
        ),
    ]
